### ISSUE TITLE
Advantages

### ISSUE THREAD

**Issue by atomkirk** [AkihiroSuda/lima#13]
Can you add advantages of using this to the readme?

speed? Is it all about speed? Can i run a dev env that includes node_modules that wont be super slow?

**Comment by AkihiroSuda** [comment]
The advantage is that you can set up a Linux machine with containerd quickly.

Performance optimization is almost left as TODO.

**Comment by atomkirk** [comment]
but why use this instead of just regular docker? Sorry, totally ignorant. I'm sure most people looking at this project will just already understand this context.

**Comment by AkihiroSuda** [comment]
> but why use this instead of just regular docker? Sorry, totally ignorant. I'm sure most people looking at this project will just already understand this context.

Docker for Mac is not free software.  Their EULA even prohibits disclosure of benchmarking result: https://www.docker.com/legal/docker-software-end-user-license-agreement

> 3. RESTRICTED ACTIVITIES
> You shall not, and shall not encourage any third party to: (a) modify, adapt, alter, translate, or create derivative works of the Licensed Software; (b) reverse-engineer, decompile, disassemble, or attempt to derive the source code for the Licensed Software, in whole or in part, except to the extent that such activities are permitted under applicable law; (c) distribute, license, sublicense, lease, rent, loan, or otherwise transfer the Licensed Software to any third party; (d) remove, alter, or obscure in any way the proprietary rights notices (including copyright, patent, and trademark notices and symbols) of Docker or its suppliers contained on or within any copies of the Licensed Software; (e) use the Licensed Software for the purpose of creating a product or service competitive with the Licensed Software; (f) use the Licensed Software for any time-sharing, outsourcing, service bureau, hosting, application service provider or like purposes; (g) disclose the results of any benchmark tests on the Licensed Software without Docker’s prior written consent; or (h) use the Licensed Software other than as described in the documentation provided therewith, or for any unlawful purpose.

On the other hand, Moby, aka Docker for Linux, is free software (Moby vs Docker is like Mozilla/Chromium vs Netscape/Chrome), but Moby lacks several novel features of containerd, such as:
- [Running a container ahead of completion of pulling the image (aka lazy-pulling, eStargz)](https://github.com/containerd/nerdctl/blob/master/docs/stargz.md)
- [Running an encrypted container](https://github.com/containerd/nerdctl/blob/master/docs/ocicrypt.md)
- Importing and exporting [OCI archives](https://github.com/opencontainers/image-spec)
