### ISSUE TITLE
Include the machine-id in the hasher to generate unique MAC addresses

### ISSUE THREAD

**Issue by jandubois** [AkihiroSuda/lima#135]
Create `osutil.MachineID()` function to return a unique id for the host system.

More info in https://github.com/AkihiroSuda/lima/pull/133#pullrequestreview-719642788

On Linux we can probably use `/var/lib/dbus/machine-id` (fallback to `/etc/machine-id`) instead.

**Comment by AkihiroSuda** [comment]
https://github.com/AkihiroSuda/lima/pull/139
