### ISSUE TITLE
Customize qemu parameters

### ISSUE THREAD

**Issue by nmeisenzahl** [AkihiroSuda/lima#14]
Hey! 

I’m asking myself whether there is an config option to customize the used qemu parameters? 
For example to add -nographic and other settings. 

Thx and greets Nico

**Comment by AkihiroSuda** [comment]
Currently hardcoded here, not customizable without modifying the source
https://github.com/AkihiroSuda/lima/blob/8028cd6720eb14aa0a887198936bc34268c8bed9/pkg/qemu/qemu.go#L87

**Comment by nmeisenzahl** [comment]
Thx for the details. Happy to close this one.
