### ISSUE TITLE
Stuck on Waiting for the essential requirement 1 of 3: "ssh"

### ISSUE THREAD

**Issue by TylerJaacks** [AkihiroSuda/lima#18]
(base) tylerjaacks in ~ λ limactl start default
INFO[0027] Attempting to download the image from "file:///Users/tylerjaacks/Downloads/hirsute-server-cloudimg-amd64.img"
curl: (37) Couldn't open file /Users/tylerjaacks/Downloads/hirsute-server-cloudimg-amd64.img
INFO[0027] Attempting to download the image from "https://cloud-images.ubuntu.com/hirsute/current/hirsute-server-cloudimg-amd64.img"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  548M  100  548M    0     0  7790k      0  0:01:12  0:01:12 --:--:-- 8069k
INFO[0099] Starting QEMU
INFO[0099] SSH: 127.0.0.1:60022
INFO[0099] Waiting for the essential requirement 1 of 3: "ssh"
INFO[0109] Waiting for the essential requirement 1 of 3: "ssh"
INFO[0119] Waiting for the essential requirement 1 of 3: "ssh"
INFO[0129] Waiting for the essential requirement 1 of 3: "ssh"
INFO[0139] Waiting for the essential requirement 1 of 3: "ssh"
INFO[0149] Waiting for the essential requirement 1 of 3: "ssh"
INFO[0159] Waiting for the essential requirement 1 of 3: "ssh"

**Comment by jajajaime** [comment]
For me it took like 10 mins to get to step 2, and 10 moreto get to step 3, but it ended up throwing another error anyway afterwards :(

**Comment by AkihiroSuda** [comment]
Please try v0.3.0.

If it still does not work, please upload `~/.lima/default/serial.log`

**Comment by AkihiroSuda** [comment]
libslirp 4.6.0 (used by QEMU) turned out to be broken: https://gitlab.freedesktop.org/slirp/libslirp/-/issues/48

Users using libslirp 4.6.0 have to downgrade libslirp to 4.5.0 (until they fixes the issue)
```console
brew uninstall qemu libslirp
wget https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a53ffe2362d2a7e55fd1a8a9bc71c1ec15bb00/Formula/libslirp.rb
brew install ./libslirp.rb
brew install qemu
```

**Comment by tnk4on** [comment]
I also got the same error using libslirp 4.6.0.
In my environment, when I run "brew install", it automatically updates to the latest version, so I had to set "HOMEBREW_NO_AUTO_UPDATE=1" before running it.

```
...
export HOMEBREW_NO_AUTO_UPDATE=1
brew install ./libslirp.rb
```

**Comment by jandubois** [comment]
@tnk4on Since you are installing from a local recipe, does it matter that brew updates its git checkout?

It should not upgrade libslirp until you run `brew upgrade`, and you can `brew pin libslirp` to prevent that. Or am I missing something?

**Comment by tnk4on** [comment]
@jandubois Sorry, I'm not familiar with `brew` so I don't know the details...
The following is the `brew insall` for the first time.
```
$ brew install ./libslirp.rb
---snip---
Warning: libslirp 4.6.0 is available and more recent than version 4.5.0.
==> Installing dependencies for libslirp: pcre
==> Installing libslirp dependency: pcre
==> Pouring pcre--8.45.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/pcre/8.45: 204 files, 5.8MB
==> Installing libslirp
==> Pouring libslirp--4.5.0.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/libslirp/4.5.0: 11 files, 331.2KB
Removing: /Users/<user>/Library/Caches/Homebrew/libslirp--4.5.0... (132.4KB)
==> Upgrading 1 dependent:
libslirp 4.5.0 -> 4.6.0
==> Upgrading libslirp
  4.5.0 -> 4.6.0
 ---snip---
 ```
 The same goes for another Mac I own. So, I had to turn off automatic updates and run it.
```
$ brew --version
Homebrew 3.1.12-85-g1cb0f0f
Homebrew/homebrew-core (git revision bba65b7ae3; last commit 2021-06-17)
Homebrew/homebrew-cask (git revision c5e395078b; last commit 2021-06-17)
```

**Comment by AkihiroSuda** [comment]
libslirp v4.6.1 with the fix is now available on homebrew
https://github.com/Homebrew/homebrew-core/pull/79479

**Comment by AkihiroSuda** [comment]
If somebody is still seeing the issue, please open a new ticket with `~/.lima/default/serial.log`.
