### ISSUE TITLE
Cannot run "arch=aarch64" on Intel Mac

### ISSUE THREAD

**Issue by jandubois** [AkihiroSuda/lima#19]
I tried on both latest Catalina and Big Sur on Intel Macs to run Lima with an ARM image. The only changes I made in the config YAML was setting `arch="aarch64"` and `cpus=1`. It starts off like this:

<img width="912" alt="Screen Shot 2021-05-18 at 3 02 19 PM" src="https://user-images.githubusercontent.com/78947/118734238-d5b04600-b7f2-11eb-9870-8ca9aedce3fe.png">

But then the screen blanks and nothing further seems to be happening (there is still a lot of CPU usage in the qemu process though):

<img width="912" alt="Screen Shot 2021-05-18 at 3 02 31 PM" src="https://user-images.githubusercontent.com/78947/118734291-f4aed800-b7f2-11eb-993d-81c3c1b7127c.png">

In desperation I tried to set `legacyBIOS=true`, but that didn't work at all.

Is this working for anybody else?

**Comment by AkihiroSuda** [comment]
ARM on Intel is very slow.
Ctrl-Alt-2 may show some progress.

**Comment by jandubois** [comment]
> ARM on Intel is very slow.

Indeed. Even slower than I expected. 😄 

> Ctrl-Alt-2 may show some progress.

Ctrl-Alt-3 does show the progress. It is easier to keep waiting when you see "something" is still moving then when you are just listening to the fans spinning up and watching a black screen...

I wonder if Intel on ARM is similarly slow, but I don't have a machine yet to test.

**Comment by bobhenkel** [comment]
I'm having this issue on Intel Mac. Am I doing something wrong?
`limactl start ubuntu.yaml
? Creating an instance "ubuntu" Proceed with the default configuration
INFO[0001] Downloading "https://github.com/containerd/nerdctl/releases/download/v0.11.1/nerdctl-full-0.11.1-linux-amd64.tar.gz" (sha256:ce7a6e119b03c3fb8ded3d46d929962fd17417bea1d5bbc07e0fce49494d8a09)
INFO[0001] Using cache "/Users/bhenkel/Library/Caches/lima/download/by-url-sha256/3304d173f1e1824e5be6cf84bf2f78825cf0db416c4c975dbb2458776942629e/data"
FATA[0002] failed to download the image, attempted 1 candidates, errors=[unsupported arch: "aarch64"]`

Here's my ubuntu.yaml
`images:
  # Hint: run `limactl prune` to invalidate the "current" cache
  - location: "https://cloud-images.ubuntu.com/hirsute/current/hirsute-server-cloudimg-arm64.img"
    arch: "aarch64"
mounts:
  - location: "~"
    writable: false
  - location: "/tmp/lima"
    writable: true
ssh:
  # localPort is changed from 60022 to avoid conflicting with the default.
  # (TODO: assign localPort automatically)
  localPort: 60028`

**Comment by ChillarAnand** [comment]
> I wonder if Intel on ARM is similarly slow, but I don't have a machine yet to test.

It is very slow. On Mac M1, I am running x86_84 & arm64 VMs with just top & k3s. It slower by ~6x.

<img width="1278" alt="Screenshot 2022-10-19 at 15 07 30" src="https://user-images.githubusercontent.com/4463796/196658152-9ea08495-eb74-4901-91c7-08667dd5a7df.png">

<img width="1278" alt="Screenshot 2022-10-19 at 15 07 41" src="https://user-images.githubusercontent.com/4463796/196658207-0663b0c8-2fd7-443c-823a-7de9172199f8.png">

**Comment by jandubois** [comment]
If you haven't see it yet, please check out https://github.com/lima-vm/lima/blob/master/docs/multi-arch.md#fast-mode-intel-containers-on-arm-vm-on-arm-host--arm-containers-on-intel-vm-on-intel-host for a way to just run the containers in the foreign arch, but the OS itself at native speed!

**Comment by ChillarAnand** [comment]
Thanks, @jandubois for the fast mode tip. In fast mode, VMs are [twice as fast](https://avilpage.com/2022/10/speedup-amd64-containers-on-arm.html) as normal mode.
