### ISSUE TITLE
Minor boot and UX improvements

### ISSUE THREAD

**Issue by Tarik02** [AkihiroSuda/lima#25]
Actually we don't need to see QEMU windows which always just shows the same image:
<img width="912" alt="Знімок екрана 2021-05-19 о 19 54 37" src="https://user-images.githubusercontent.com/12175048/118853082-0cae5680-b8dc-11eb-826b-1667592447bc.png">

This can be removed with `-nographic` option and omitting `-vga none` and `-device ramfb` options.

The second thing it is worth to mention is boot (BIOS) timeout (3 seconds) which can be bypassed using `-boot "splash-time=0,menu=on"` option.

But these options should be configurable by `start` command flag and (maybe) by VM config. They're pretty useful for troubleshooting.

**Comment by AkihiroSuda** [comment]
> This can be removed with -nographic option and omitting -vga none and -device ramfb options.

SGTM, but the default behavior should stay showing the vga (for ease of debugging, mostly)

> The second thing it is worth to mention is boot (BIOS) timeout (3 seconds) which can be bypassed using -boot "splash-time=0,menu=on" option.

SGTM
