### ISSUE TITLE
Daemon mode and stop command

### ISSUE THREAD

**Issue by Tarik02** [AkihiroSuda/lima#26]
Start command needs terminal to be left open to work and sending interrupt signal kills QEMU.

There is place for a few improvements:
- Make `start` command to daemonize process by default: the process detaches making QEMU running in background.
- Add `stop` command that makes VM gracefully shutdown. Can be implemented by communicating with guest agent and calling shutdown command on guest.

**Comment by AkihiroSuda** [comment]
Yes, I’m planning to work on this after replacing sshfs with 9p (#1)

**Comment by AkihiroSuda** [comment]
Coming soon: #46

**Comment by AkihiroSuda** [comment]
Released v0.3.0 with background `limactl start` & `limactl stop`

https://github.com/AkihiroSuda/lima/releases/tag/v0.3.0
