### ISSUE TITLE
An option to specify custom QEMU installation (prefix)

### ISSUE THREAD

**Issue by Tarik02** [AkihiroSuda/lima#27]
There should be an option to use custom QEMU installation that is located in some directory. It is not always convenient to have system-global QEMU.

This setting needs to be configured per VM (in config).

Currently there's 3 things that are used from QEMU:
- `qemu-system-`
- `qemu-img`
- firmware (UEFI)

**Comment by AkihiroSuda** [comment]
Does setting $PATH work for you?

**Comment by Tarik02** [comment]
> Does setting $PATH work for you?

I did not try to do this, I just hardcoded paths to the sources. But without configuration option it is going to be painful PATH setting all the time thing.

**Comment by AkihiroSuda** [comment]
PR: https://github.com/AkihiroSuda/lima/pull/80
