### ISSUE TITLE
How to add another distro

### ISSUE THREAD

**Issue by jeremyjjbrown** [AkihiroSuda/lima#32]
I might be interested in adding Arch Linux. What does it take and where do I look?

**Comment by christian-korneck** [comment]
@jeremyjjbrown have you seen [this section](https://github.com/AkihiroSuda/lima#can-i-run-non-ubuntu-guests) in the README? I haven't tried it but I could imagine the official [arch image for openstack](https://wiki.archlinux.org/title/OpenStack#Available_images) might work?

**Comment by jeremyjjbrown** [comment]
Thanks @christian-korneck I somehow didn't catch that section. I might give this a try if I get some hacking time.

**Comment by AkihiroSuda** [comment]
Arch Linux image will be included in the next version https://github.com/AkihiroSuda/lima/pull/88
