### ISSUE TITLE
Homebrew

### ISSUE THREAD

**Issue by SebDanielsson** [AkihiroSuda/lima#37]
Would be nice if lima was on Homebrew!

**Comment by AkihiroSuda** [comment]
https://github.com/Homebrew/homebrew-core/pull/77739

> GitHub repository too new (<30 days old)

We have to wait for 9 days at least

**Comment by AkihiroSuda** [comment]
cc @HappyTobi

**Comment by HappyTobi** [comment]
I will reopen the pr in 9 days

**Comment by AkihiroSuda** [comment]
Thanks!

**Comment by HappyTobi** [comment]
Will reopen the pr today

**Comment by HappyTobi** [comment]
PR was created: https://github.com/Homebrew/homebrew-core/pull/79279

**Comment by AkihiroSuda** [comment]
Thanks!

**Comment by HappyTobi** [comment]
@AkihiroSuda issue can be closed the homebrew pr was merged.

**Comment by AkihiroSuda** [comment]
Thank you!
