### ISSUE TITLE
Unable to Build using make (package embed is not in GOROOT)

### ISSUE THREAD

**Issue by TylerJaacks** [AkihiroSuda/lima#6]
(base) tylerjaacks in ~/Desktop/lima on master λ make
mkdir -p _output/bin
cp -a ./cmd/lima _output/bin/lima
CGO_ENABLED=0 go build -ldflags="-s -w -X github.com/AkihiroSuda/lima/pkg/version.Version=v0.1.0-2-g0ebf6f0" -o _output/bin/limactl ./cmd/limactl
pkg/limayaml/template.go:4:2: package embed is not in GOROOT (/usr/local/go/src/embed)
pkg/cidata/cidata.go:4:2: package io/fs is not in GOROOT (/usr/local/go/src/io/fs)
make: *** [Makefile:35: _output/bin/limactl] Error 1

**Comment by AkihiroSuda** [comment]
You need Go 1.16
