### ISSUE TITLE
[ARM] Not able to run containers: `process_linux.go:722: waiting for init preliminary setup caused: unexpected 123 != 0: unknown`

### ISSUE THREAD

**Issue by idrissneumann** [AkihiroSuda/lima#79]
Here's the error I get:

```shell
failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:722: waiting for init preliminary setup caused: unexpected 123 != 0: unknown
```

Reproduced with `docker-compose` and `nerdctl`:

<img width="1436" alt="Screenshot 2021-06-24 at 07 30 52" src="https://user-images.githubusercontent.com/12884347/123213753-4c112980-d4be-11eb-9e96-f01254007273.png">

<img width="1438" alt="Screenshot 2021-06-24 at 07 31 06" src="https://user-images.githubusercontent.com/12884347/123213763-52070a80-d4be-11eb-9fa0-2ebe4ad4ce27.png">

NB : I use a Macbook pro 13 with the M1 ship.

Thanks in advance.

**Comment by AkihiroSuda** [comment]
Thanks for reporting. This seems an issue of runc, could you report to https://github.com/opencontainers/runc/issues ?

**Comment by AkihiroSuda** [comment]
opened https://github.com/opencontainers/runc/issues/3037
