### ISSUE TITLE
/usr/local/bin/lima: line 4: realpath: command not found on MacOS 10.14

### ISSUE THREAD

**Issue by nmcain** [AkihiroSuda/lima#8]
I'm trying to run lima on my Macbook pro, but lima is complaining about a missing command. Do I need some sort of additional dependency to run this?

**Comment by AkihiroSuda** [comment]
brew install coreutils

https://github.com/AkihiroSuda/lima/pull/7

**Comment by bric3** [comment]
@nmcain I don't knw where you extracted the package but I had the same problem if I extracted the archive somewhere else. To work around this I simply created symlinks.

```shell
$ take cd /usr/local/opt/lima
$ tar zxf lima-0.1.0-Darwin-x86_64.tar.gz
$ ln -sf /usr/local/opt/lima/bin/limactl /usr/local/bin/limactl
$ ln -sf /usr/local/opt/lima/bin/lima /usr/local/bin/lima
$ ln -sf /usr/local/opt/lima/share/lima /usr/local/share/lima
```
